/* fwp runtime: gRPC over HTTP/2 cleartext (h2c, prior knowledge) and the
 * protobuf transcoder used by services (see docs/services.md).
 *
 *   - HPACK (RFC 7541): static and dynamic tables, Huffman decoding; the
 *     encoder writes literals without indexing.
 *   - HTTP/2 (RFC 9113): framing, SETTINGS, PING, WINDOW_UPDATE, GOAWAY,
 *     RST_STREAM, CONTINUATION and flow control.
 *   - gRPC: length-prefixed messages, grpc-status and grpc-message.
 *   - Protobuf: transcoding between the canonical binary encoding of fwp
 *     values and the protobuf wire format, driven by a schema of integers
 *     generated by the compiler (src/protobuf.rs, which implements the same
 *     algorithm for the interpreter).
 *
 * This file depends only on the C library, so the test suite can compile
 * it on its own (tests/services/h2_test.c). It is embedded only in
 * programs that call or serve services. */

#ifndef __wasi__
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
#endif

/* ------------------------------------------------------------------ buffers */

typedef struct { unsigned char *d; size_t len, cap; } h2_buf;

static void h2b_reserve(h2_buf *b, size_t n) {
    if (b->len + n <= b->cap) return;
    size_t c = b->cap ? b->cap : 256;
    while (c < b->len + n) c *= 2;
    b->d = (unsigned char *)realloc(b->d, c);
    if (!b->d) { fprintf(stderr, "fwp: out of memory\n"); exit(102); }
    b->cap = c;
}
static void h2b_put(h2_buf *b, const void *p, size_t n) {
    if (!n) return;
    h2b_reserve(b, n);
    memcpy(b->d + b->len, p, n);
    b->len += n;
}
static void h2b_byte(h2_buf *b, unsigned c) { unsigned char x = (unsigned char)c; h2b_put(b, &x, 1); }
static void h2b_drop(h2_buf *b, size_t n) {
    if (n >= b->len) { b->len = 0; return; }
    memmove(b->d, b->d + n, b->len - n);
    b->len -= n;
}
static void h2b_free(h2_buf *b) { free(b->d); b->d = 0; b->len = b->cap = 0; }
static void h2b_be32(h2_buf *b, uint32_t x) {
    unsigned char t[4] = {(unsigned char)(x >> 24), (unsigned char)(x >> 16), (unsigned char)(x >> 8), (unsigned char)x};
    h2b_put(b, t, 4);
}
static uint32_t h2_rd32(const unsigned char *p) {
    return (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | p[3];
}

static char h2_err[512];
static int h2_fail(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(h2_err, sizeof h2_err, fmt, ap);
    va_end(ap);
    return 0;
}

/* -------------------------------------------------------------------- HPACK */

static const char *const h2_static[61][2] = {
    {":authority", ""}, {":method", "GET"}, {":method", "POST"}, {":path", "/"},
    {":path", "/index.html"}, {":scheme", "http"}, {":scheme", "https"}, {":status", "200"},
    {":status", "204"}, {":status", "206"}, {":status", "304"}, {":status", "400"},
    {":status", "404"}, {":status", "500"}, {"accept-charset", ""}, {"accept-encoding", "gzip, deflate"},
    {"accept-language", ""}, {"accept-ranges", ""}, {"accept", ""}, {"access-control-allow-origin", ""},
    {"age", ""}, {"allow", ""}, {"authorization", ""}, {"cache-control", ""},
    {"content-disposition", ""}, {"content-encoding", ""}, {"content-language", ""}, {"content-length", ""},
    {"content-location", ""}, {"content-range", ""}, {"content-type", ""}, {"cookie", ""},
    {"date", ""}, {"etag", ""}, {"expect", ""}, {"expires", ""},
    {"from", ""}, {"host", ""}, {"if-match", ""}, {"if-modified-since", ""},
    {"if-none-match", ""}, {"if-range", ""}, {"if-unmodified-since", ""}, {"last-modified", ""},
    {"link", ""}, {"location", ""}, {"max-forwards", ""}, {"proxy-authenticate", ""},
    {"proxy-authorization", ""}, {"range", ""}, {"referer", ""}, {"refresh", ""},
    {"retry-after", ""}, {"server", ""}, {"set-cookie", ""}, {"strict-transport-security", ""},
    {"transfer-encoding", ""}, {"user-agent", ""}, {"vary", ""}, {"via", ""},
    {"www-authenticate", ""},
};

/* RFC 7541 Appendix B; EOS (0x3fffffff, 30 bits) is added when the tree
 * is built */
static const uint32_t fwp_huff_codes[256] = {
    0x1ff8u, 0x7fffd8u, 0xfffffe2u, 0xfffffe3u, 0xfffffe4u, 0xfffffe5u, 0xfffffe6u, 0xfffffe7u,
    0xfffffe8u, 0xffffeau, 0x3ffffffcu, 0xfffffe9u, 0xfffffeau, 0x3ffffffdu, 0xfffffebu, 0xfffffecu,
    0xfffffedu, 0xfffffeeu, 0xfffffefu, 0xffffff0u, 0xffffff1u, 0xffffff2u, 0x3ffffffeu, 0xffffff3u,
    0xffffff4u, 0xffffff5u, 0xffffff6u, 0xffffff7u, 0xffffff8u, 0xffffff9u, 0xffffffau, 0xffffffbu,
    0x14u, 0x3f8u, 0x3f9u, 0xffau, 0x1ff9u, 0x15u, 0xf8u, 0x7fau,
    0x3fau, 0x3fbu, 0xf9u, 0x7fbu, 0xfau, 0x16u, 0x17u, 0x18u,
    0x0u, 0x1u, 0x2u, 0x19u, 0x1au, 0x1bu, 0x1cu, 0x1du,
    0x1eu, 0x1fu, 0x5cu, 0xfbu, 0x7ffcu, 0x20u, 0xffbu, 0x3fcu,
    0x1ffau, 0x21u, 0x5du, 0x5eu, 0x5fu, 0x60u, 0x61u, 0x62u,
    0x63u, 0x64u, 0x65u, 0x66u, 0x67u, 0x68u, 0x69u, 0x6au,
    0x6bu, 0x6cu, 0x6du, 0x6eu, 0x6fu, 0x70u, 0x71u, 0x72u,
    0xfcu, 0x73u, 0xfdu, 0x1ffbu, 0x7fff0u, 0x1ffcu, 0x3ffcu, 0x22u,
    0x7ffdu, 0x3u, 0x23u, 0x4u, 0x24u, 0x5u, 0x25u, 0x26u,
    0x27u, 0x6u, 0x74u, 0x75u, 0x28u, 0x29u, 0x2au, 0x7u,
    0x2bu, 0x76u, 0x2cu, 0x8u, 0x9u, 0x2du, 0x77u, 0x78u,
    0x79u, 0x7au, 0x7bu, 0x7ffeu, 0x7fcu, 0x3ffdu, 0x1ffdu, 0xffffffcu,
    0xfffe6u, 0x3fffd2u, 0xfffe7u, 0xfffe8u, 0x3fffd3u, 0x3fffd4u, 0x3fffd5u, 0x7fffd9u,
    0x3fffd6u, 0x7fffdau, 0x7fffdbu, 0x7fffdcu, 0x7fffddu, 0x7fffdeu, 0xffffebu, 0x7fffdfu,
    0xffffecu, 0xffffedu, 0x3fffd7u, 0x7fffe0u, 0xffffeeu, 0x7fffe1u, 0x7fffe2u, 0x7fffe3u,
    0x7fffe4u, 0x1fffdcu, 0x3fffd8u, 0x7fffe5u, 0x3fffd9u, 0x7fffe6u, 0x7fffe7u, 0xffffefu,
    0x3fffdau, 0x1fffddu, 0xfffe9u, 0x3fffdbu, 0x3fffdcu, 0x7fffe8u, 0x7fffe9u, 0x1fffdeu,
    0x7fffeau, 0x3fffddu, 0x3fffdeu, 0xfffff0u, 0x1fffdfu, 0x3fffdfu, 0x7fffebu, 0x7fffecu,
    0x1fffe0u, 0x1fffe1u, 0x3fffe0u, 0x1fffe2u, 0x7fffedu, 0x3fffe1u, 0x7fffeeu, 0x7fffefu,
    0xfffeau, 0x3fffe2u, 0x3fffe3u, 0x3fffe4u, 0x7ffff0u, 0x3fffe5u, 0x3fffe6u, 0x7ffff1u,
    0x3ffffe0u, 0x3ffffe1u, 0xfffebu, 0x7fff1u, 0x3fffe7u, 0x7ffff2u, 0x3fffe8u, 0x1ffffecu,
    0x3ffffe2u, 0x3ffffe3u, 0x3ffffe4u, 0x7ffffdeu, 0x7ffffdfu, 0x3ffffe5u, 0xfffff1u, 0x1ffffedu,
    0x7fff2u, 0x1fffe3u, 0x3ffffe6u, 0x7ffffe0u, 0x7ffffe1u, 0x3ffffe7u, 0x7ffffe2u, 0xfffff2u,
    0x1fffe4u, 0x1fffe5u, 0x3ffffe8u, 0x3ffffe9u, 0xffffffdu, 0x7ffffe3u, 0x7ffffe4u, 0x7ffffe5u,
    0xfffecu, 0xfffff3u, 0xfffedu, 0x1fffe6u, 0x3fffe9u, 0x1fffe7u, 0x1fffe8u, 0x7ffff3u,
    0x3fffeau, 0x3fffebu, 0x1ffffeeu, 0x1ffffefu, 0xfffff4u, 0xfffff5u, 0x3ffffeau, 0x7ffff4u,
    0x3ffffebu, 0x7ffffe6u, 0x3ffffecu, 0x3ffffedu, 0x7ffffe7u, 0x7ffffe8u, 0x7ffffe9u, 0x7ffffeau,
    0x7ffffebu, 0xffffffeu, 0x7ffffecu, 0x7ffffedu, 0x7ffffeeu, 0x7ffffefu, 0x7fffff0u, 0x3ffffeeu,
};
static const uint8_t fwp_huff_lens[256] = {
    13, 23, 28, 28, 28, 28, 28, 28, 28, 24, 30, 28, 28, 30, 28, 28,
    28, 28, 28, 28, 28, 28, 30, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    6, 10, 10, 12, 13, 6, 8, 11, 10, 10, 8, 11, 8, 6, 6, 6,
    5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 8, 15, 6, 12, 10,
    13, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 8, 13, 19, 13, 14, 6,
    15, 5, 6, 5, 6, 5, 6, 6, 6, 5, 7, 7, 6, 6, 6, 5,
    6, 7, 6, 5, 5, 6, 7, 7, 7, 7, 7, 15, 11, 14, 13, 28,
    20, 22, 20, 20, 22, 22, 22, 23, 22, 23, 23, 23, 23, 23, 24, 23,
    24, 24, 22, 23, 24, 23, 23, 23, 23, 21, 22, 23, 22, 23, 23, 24,
    22, 21, 20, 22, 22, 23, 23, 21, 23, 22, 22, 24, 21, 22, 23, 23,
    21, 21, 22, 21, 23, 22, 23, 23, 20, 22, 22, 22, 23, 22, 22, 23,
    26, 26, 20, 19, 22, 23, 22, 25, 26, 26, 26, 27, 27, 26, 24, 25,
    19, 21, 26, 27, 27, 26, 27, 24, 21, 21, 26, 26, 28, 27, 27, 27,
    20, 24, 20, 21, 22, 21, 21, 23, 22, 22, 25, 25, 24, 24, 26, 23,
    26, 27, 26, 26, 27, 27, 27, 27, 27, 28, 27, 27, 27, 27, 27, 26,
};
/* the decoding tree: internal nodes hold child indices, leaves -(sym + 1) */
static int h2_huff_tree[600][2];
static int h2_huff_nodes = 0;

static void h2_huff_add(uint32_t code, int len, int sym) {
    int n = 0;
    for (int k = len - 1; k >= 0; k--) {
        int bit = (int)((code >> k) & 1);
        if (k == 0) {
            h2_huff_tree[n][bit] = -(sym + 1);
        } else {
            if (h2_huff_tree[n][bit] == 0) {
                h2_huff_tree[h2_huff_nodes][0] = h2_huff_tree[h2_huff_nodes][1] = 0;
                h2_huff_tree[n][bit] = h2_huff_nodes++;
            }
            n = h2_huff_tree[n][bit];
        }
    }
}

static int h2_huff_decode(const unsigned char *p, size_t n, h2_buf *out) {
    if (!h2_huff_nodes) {
        h2_huff_nodes = 1;
        h2_huff_tree[0][0] = h2_huff_tree[0][1] = 0;
        for (int s = 0; s < 256; s++) h2_huff_add(fwp_huff_codes[s], fwp_huff_lens[s], s);
        h2_huff_add(0x3fffffffu, 30, 256);
    }
    int node = 0, pending = 0, ones = 1;
    for (size_t i = 0; i < n; i++) {
        for (int k = 7; k >= 0; k--) {
            int bit = (p[i] >> k) & 1;
            pending++;
            ones &= bit;
            int next = h2_huff_tree[node][bit];
            if (next < 0) {
                int sym = -next - 1;
                if (sym == 256) return h2_fail("hpack: EOS in Huffman string");
                h2b_byte(out, (unsigned)sym);
                node = 0;
                pending = 0;
                ones = 1;
            } else if (next == 0) {
                return h2_fail("hpack: bad Huffman code");
            } else {
                node = next;
            }
        }
    }
    if (pending > 7 || !ones) return h2_fail("hpack: bad Huffman padding");
    return 1;
}

typedef struct { char *name, *value; } h2_hdr;
typedef struct { h2_hdr *v; size_t n, cap; } h2_hdrs;

static void h2_hdrs_add(h2_hdrs *h, const char *name, size_t nl, const char *value, size_t vl) {
    if (h->n == h->cap) {
        h->cap = h->cap ? h->cap * 2 : 8;
        h->v = (h2_hdr *)realloc(h->v, h->cap * sizeof(h2_hdr));
    }
    h2_hdr *e = &h->v[h->n++];
    e->name = (char *)malloc(nl + 1);
    memcpy(e->name, name, nl);
    e->name[nl] = 0;
    e->value = (char *)malloc(vl + 1);
    memcpy(e->value, value, vl);
    e->value[vl] = 0;
}

static void h2_hdrs_free(h2_hdrs *h) {
    for (size_t i = 0; i < h->n; i++) { free(h->v[i].name); free(h->v[i].value); }
    free(h->v);
    h->v = 0;
    h->n = h->cap = 0;
}

/* the value of the last header with this name, or 0 */
static const char *h2_get(const h2_hdrs *h, const char *name) {
    for (size_t i = h->n; i > 0; i--)
        if (strcmp(h->v[i - 1].name, name) == 0) return h->v[i - 1].value;
    return 0;
}

/* a decoder: the dynamic table (newest first) and its size */
typedef struct { h2_hdrs t; size_t size, max, limit; } h2_hpack;

static void h2_hpack_init(h2_hpack *d) { memset(d, 0, sizeof *d); d->max = d->limit = 4096; }
static void h2_hpack_free(h2_hpack *d) { h2_hdrs_free(&d->t); }

static void h2_hpack_evict(h2_hpack *d) {
    while (d->size > d->max && d->t.n > 0) {
        h2_hdr *e = &d->t.v[d->t.n - 1];
        d->size -= strlen(e->name) + strlen(e->value) + 32;
        free(e->name);
        free(e->value);
        d->t.n--;
    }
}

static void h2_hpack_insert(h2_hpack *d, const char *name, const char *value) {
    h2_hdrs_add(&d->t, name, strlen(name), value, strlen(value));
    h2_hdr e = d->t.v[d->t.n - 1];
    memmove(d->t.v + 1, d->t.v, (d->t.n - 1) * sizeof(h2_hdr));
    d->t.v[0] = e;
    d->size += strlen(name) + strlen(value) + 32;
    h2_hpack_evict(d);
}

static int h2_hpack_entry(h2_hpack *d, uint64_t i, const char **name, const char **value) {
    if (i == 0) return h2_fail("hpack: index 0");
    if (i <= 61) { *name = h2_static[i - 1][0]; *value = h2_static[i - 1][1]; return 1; }
    if (i - 62 >= d->t.n) return h2_fail("hpack: index %llu out of range", (unsigned long long)i);
    *name = d->t.v[i - 62].name;
    *value = d->t.v[i - 62].value;
    return 1;
}

static int h2_int(const unsigned char *b, size_t n, size_t *i, int prefix, uint64_t *x) {
    uint64_t mask = ((uint64_t)1 << prefix) - 1;
    if (*i >= n) return h2_fail("hpack: truncated");
    *x = b[(*i)++] & mask;
    if (*x < mask) return 1;
    for (int shift = 0;; shift += 7) {
        if (*i >= n) return h2_fail("hpack: truncated integer");
        if (shift > 56) return h2_fail("hpack: integer overflow");
        unsigned char c = b[(*i)++];
        *x += (uint64_t)(c & 0x7f) << shift;
        if (!(c & 0x80)) return 1;
    }
}

/* a string literal, NUL-terminated in `out` */
static int h2_str(const unsigned char *b, size_t n, size_t *i, h2_buf *out) {
    out->len = 0;
    if (*i >= n) return h2_fail("hpack: truncated");
    int huff = b[*i] & 0x80;
    uint64_t len;
    if (!h2_int(b, n, i, 7, &len)) return 0;
    if (len > n - *i) return h2_fail("hpack: truncated string");
    if (huff) { if (!h2_huff_decode(b + *i, (size_t)len, out)) return 0; }
    else h2b_put(out, b + *i, (size_t)len);
    *i += (size_t)len;
    h2b_byte(out, 0);
    out->len--;
    return 1;
}

static int h2_hpack_decode(h2_hpack *d, const unsigned char *b, size_t n, h2_hdrs *out) {
    size_t i = 0;
    h2_buf name = {0}, value = {0};
    int ok = 1;
    while (ok && i < n) {
        unsigned char c = b[i];
        uint64_t x;
        const char *nm, *vl;
        if (c & 0x80) {
            ok = h2_int(b, n, &i, 7, &x) && h2_hpack_entry(d, x, &nm, &vl);
            if (ok) h2_hdrs_add(out, nm, strlen(nm), vl, strlen(vl));
        } else if ((c & 0xe0) == 0x20) {
            ok = h2_int(b, n, &i, 5, &x);
            if (ok && x > d->limit) ok = h2_fail("hpack: table size update above the limit");
            if (ok) { d->max = (size_t)x; h2_hpack_evict(d); }
        } else {
            int indexing = (c & 0x40) != 0;
            ok = h2_int(b, n, &i, indexing ? 6 : 4, &x);
            if (!ok) break;
            if (x == 0) {
                ok = h2_str(b, n, &i, &name);
            } else {
                ok = h2_hpack_entry(d, x, &nm, &vl);
                name.len = 0;
                if (ok) { h2b_put(&name, nm, strlen(nm) + 1); name.len--; }
            }
            ok = ok && h2_str(b, n, &i, &value);
            if (!ok) break;
            h2_hdrs_add(out, (char *)name.d, name.len, (char *)value.d, value.len);
            if (indexing) h2_hpack_insert(d, (char *)name.d, (char *)value.d);
        }
    }
    h2b_free(&name);
    h2b_free(&value);
    return ok;
}

static void h2_put_int(h2_buf *b, unsigned flags, int prefix, uint64_t x) {
    uint64_t max = ((uint64_t)1 << prefix) - 1;
    if (x < max) { h2b_byte(b, flags | (unsigned)x); return; }
    h2b_byte(b, flags | (unsigned)max);
    x -= max;
    while (x >= 128) { h2b_byte(b, (unsigned)(x % 128) | 0x80); x /= 128; }
    h2b_byte(b, (unsigned)x);
}

/* a literal header field without indexing, with a new name */
static void h2_hpack_lit(h2_buf *b, const char *name, const char *value) {
    size_t nl = strlen(name), vl = strlen(value);
    h2b_byte(b, 0);
    h2_put_int(b, 0, 7, nl);
    h2b_put(b, name, nl);
    h2_put_int(b, 0, 7, vl);
    h2b_put(b, value, vl);
}

/* ------------------------------------------------------------------- frames */

enum { H2_DATA = 0, H2_HEADERS = 1, H2_RST_STREAM = 3, H2_SETTINGS = 4, H2_PING = 6, H2_GOAWAY = 7,
       H2_WINDOW_UPDATE = 8, H2_CONTINUATION = 9 };
enum { H2_END_STREAM = 1, H2_ACK = 1, H2_END_HEADERS = 4, H2_PADDED = 8, H2_PRIORITY = 0x20 };
#define H2_OUR_WINDOW (1u << 30)
#define H2_MAX_FRAME (1u << 24)
static const char h2_preface[] = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n";

static void h2_frame(h2_buf *b, int type, int flags, uint32_t stream, const void *p, size_t n) {
    unsigned char h[9] = {(unsigned char)(n >> 16), (unsigned char)(n >> 8), (unsigned char)n, (unsigned char)type,
                          (unsigned char)flags, (unsigned char)((stream >> 24) & 0x7f), (unsigned char)(stream >> 16),
                          (unsigned char)(stream >> 8), (unsigned char)stream};
    h2b_put(b, h, 9);
    h2b_put(b, p, n);
}

typedef struct { int type, flags; uint32_t stream; const unsigned char *p; size_t n; } h2_fr;

/* 1: a frame of `size` bytes is at the start of the buffer; 0: need more;
 * -1: malformed */
static int h2_parse(const h2_buf *b, h2_fr *f, size_t *size) {
    if (b->len < 9) return 0;
    size_t n = (size_t)b->d[0] << 16 | (size_t)b->d[1] << 8 | b->d[2];
    if (n > H2_MAX_FRAME) return -1;
    if (b->len < 9 + n) return 0;
    f->type = b->d[3];
    f->flags = b->d[4];
    f->stream = h2_rd32(b->d + 5) & 0x7fffffffu;
    f->p = b->d + 9;
    f->n = n;
    *size = 9 + n;
    return 1;
}

/* the payload of DATA or HEADERS without padding and priority */
static int h2_unpad(const h2_fr *f, const unsigned char **p, size_t *n) {
    *p = f->p;
    *n = f->n;
    size_t pad = 0;
    if (f->flags & H2_PADDED) {
        if (*n < 1) return 0;
        pad = (*p)[0];
        (*p)++;
        (*n)--;
    }
    if (f->type == H2_HEADERS && (f->flags & H2_PRIORITY)) {
        if (*n < 5) return 0;
        *p += 5;
        *n -= 5;
    }
    if (pad > *n) return 0;
    *n -= pad;
    return 1;
}

static void h2_header_frames(h2_buf *b, uint32_t stream, const h2_buf *block, int end_stream, size_t max) {
    size_t off = 0;
    int first = 1;
    do {
        size_t k = block->len - off > max ? max : block->len - off;
        int last = off + k == block->len;
        int flags = last ? H2_END_HEADERS : 0;
        if (first && end_stream) flags |= H2_END_STREAM;
        h2_frame(b, first ? H2_HEADERS : H2_CONTINUATION, flags, stream, block->d ? block->d + off : 0, k);
        off += k;
        first = 0;
    } while (off < block->len);
}

static void h2_our_settings(h2_buf *b) {
    unsigned char s[12] = {0, 2, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0};
    s[8] = (unsigned char)(H2_OUR_WINDOW >> 24);
    s[9] = (unsigned char)(H2_OUR_WINDOW >> 16);
    s[10] = (unsigned char)(H2_OUR_WINDOW >> 8);
    s[11] = (unsigned char)H2_OUR_WINDOW;
    h2_frame(b, H2_SETTINGS, 0, 0, s, 12);
    h2_buf w = {0};
    h2b_be32(&w, H2_OUR_WINDOW - 65535);
    h2_frame(b, H2_WINDOW_UPDATE, 0, 0, w.d, 4);
    h2b_free(&w);
}

typedef struct { size_t max_frame; int64_t init_window; } h2_peer;

/* apply a SETTINGS payload; *delta is the change of the initial window */
static int h2_settings(h2_peer *pe, const unsigned char *p, size_t n, int64_t *delta) {
    *delta = 0;
    if (n % 6) return h2_fail("bad SETTINGS frame");
    for (size_t i = 0; i < n; i += 6) {
        unsigned id = (unsigned)p[i] << 8 | p[i + 1];
        uint32_t v = h2_rd32(p + i + 2);
        if (id == 4) {
            if (v > 0x7fffffffu) return h2_fail("bad initial window size");
            *delta += (int64_t)v - pe->init_window;
            pe->init_window = v;
        } else if (id == 5) {
            if (v < 16384 || v > 16777215) return h2_fail("bad max frame size");
            pe->max_frame = v;
        }
    }
    return 1;
}

/* --------------------------------------------------------------------- gRPC */

enum { GRPC_INVALID_ARGUMENT = 3, GRPC_FAILED_PRECONDITION = 9, GRPC_UNIMPLEMENTED = 12,
       GRPC_INTERNAL = 13, GRPC_UNAVAILABLE = 14 };

static void h2_grpc_frame(h2_buf *b, const unsigned char *msg, size_t n) {
    h2b_byte(b, 0);
    h2b_be32(b, (uint32_t)n);
    h2b_put(b, msg, n);
}

static int h2_grpc_unframe(const h2_buf *body, const unsigned char **msg, size_t *n) {
    if (body->len < 5) return h2_fail("missing gRPC message");
    if (body->d[0] != 0) return h2_fail("compressed gRPC messages are not supported");
    *n = h2_rd32(body->d + 1);
    if (body->len != 5 + *n) return h2_fail("expected exactly one gRPC message");
    *msg = body->d + 5;
    return 1;
}

static void h2_pct_encode(h2_buf *b, const char *s) {
    static const char hex[] = "0123456789ABCDEF";
    for (; *s; s++) {
        unsigned char c = (unsigned char)*s;
        if (c >= 0x20 && c < 0x7f && c != '%') h2b_byte(b, c);
        else { h2b_byte(b, '%'); h2b_byte(b, (unsigned)hex[c >> 4]); h2b_byte(b, (unsigned)hex[c & 15]); }
    }
    h2b_byte(b, 0);
    b->len--;
}

static int h2_hexval(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static void h2_pct_decode(char *s) {
    char *w = s;
    for (const char *r = s; *r;) {
        if (r[0] == '%' && r[1] && r[2] && h2_hexval(r[1]) >= 0 && h2_hexval(r[2]) >= 0) {
            *w++ = (char)(h2_hexval(r[1]) * 16 + h2_hexval(r[2]));
            r += 3;
        } else {
            *w++ = *r++;
        }
    }
    *w = 0;
}

/* -------------------------------------------------------------- socket I/O */

static int h2_send_all(int fd, const unsigned char *p, size_t n) {
    while (n > 0) {
        ssize_t k = send(fd, p, n, MSG_NOSIGNAL);
        if (k < 0) {
            if (errno == EINTR) continue;
            return 0;
        }
        p += k;
        n -= (size_t)k;
    }
    return 1;
}

/* connect to "host:port" (or "[v6]:port") */
static int h2_connect(const char *addr) {
    char host[256];
    const char *colon = strrchr(addr, ':');
    if (!colon || (size_t)(colon - addr) >= sizeof host) { h2_fail("bad address `%s`", addr); return -1; }
    memcpy(host, addr, (size_t)(colon - addr));
    host[colon - addr] = 0;
    char *h = host;
    if (h[0] == '[' && h[strlen(h) - 1] == ']') { h[strlen(h) - 1] = 0; h++; }
    struct addrinfo hints, *res = 0;
    memset(&hints, 0, sizeof hints);
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    int rc = getaddrinfo(h, colon + 1, &hints, &res);
    if (rc != 0) { h2_fail("cannot resolve %s: %s", addr, gai_strerror(rc)); return -1; }
    int fd = -1, err = 0;
    for (struct addrinfo *a = res; a; a = a->ai_next) {
        fd = socket(a->ai_family, a->ai_socktype | SOCK_CLOEXEC, a->ai_protocol);
        if (fd < 0) { err = errno; continue; }
        if (connect(fd, a->ai_addr, a->ai_addrlen) == 0) break;
        err = errno;
        close(fd);
        fd = -1;
    }
    freeaddrinfo(res);
    if (fd < 0) { h2_fail("cannot connect to %s: %s", addr, strerror(err)); return -1; }
    int one = 1;
    setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof one);
    return fd;
}

/* ------------------------------------------------------------------- client */

typedef struct h2_client {
    int fd;
    char addr[256];
    h2_hpack dec;
    h2_peer peer;
    int64_t conn_window, stream_window;
    uint32_t next_stream;
    h2_buf in;
    int dead;
    struct h2_client *next;
} h2_client;

static h2_client *h2_pool = 0; /* idle connections */

static void h2_client_free(h2_client *c) {
    if (c->fd >= 0) close(c->fd);
    h2_hpack_free(&c->dec);
    h2b_free(&c->in);
    free(c);
}

static h2_client *h2_client_new(const char *addr) {
    int fd = h2_connect(addr);
    if (fd < 0) return 0;
    h2_client *c = (h2_client *)calloc(1, sizeof *c);
    c->fd = fd;
    snprintf(c->addr, sizeof c->addr, "%s", addr);
    h2_hpack_init(&c->dec);
    c->peer.max_frame = 16384;
    c->peer.init_window = 65535;
    c->conn_window = 65535;
    c->next_stream = 1;
    h2_buf hello = {0};
    h2b_put(&hello, h2_preface, sizeof h2_preface - 1);
    h2_our_settings(&hello);
    int ok = h2_send_all(fd, hello.d, hello.len);
    h2b_free(&hello);
    if (!ok) { h2_fail("cannot send to %s: %s", addr, strerror(errno)); h2_client_free(c); return 0; }
    return c;
}

/* call failure kinds */
enum { H2_OK = 0, H2_TRANSPORT = -1, H2_RETRY = -2 };

static int h2_client_send(h2_client *c, const h2_buf *b, int retry) {
    if (h2_send_all(c->fd, b->d, b->len)) return H2_OK;
    c->dead = 1;
    h2_fail("cannot send to %s: %s", c->addr, strerror(errno));
    return retry ? H2_RETRY : H2_TRANSPORT;
}

/* read the next frame into *f (valid until the next read); returns H2_OK
 * or a failure kind */
static int h2_client_read(h2_client *c, h2_fr *f, size_t *consumed, int retry) {
    if (*consumed) { h2b_drop(&c->in, *consumed); *consumed = 0; }
    for (;;) {
        int r = h2_parse(&c->in, f, consumed);
        if (r > 0) return H2_OK;
        if (r < 0) { c->dead = 1; h2_fail("bad frame from %s", c->addr); return H2_TRANSPORT; }
        h2b_reserve(&c->in, 16384);
        ssize_t k = recv(c->fd, c->in.d + c->in.len, 16384, 0);
        if (k == 0) { c->dead = 1; h2_fail("connection to %s closed", c->addr); return retry ? H2_RETRY : H2_TRANSPORT; }
        if (k < 0) {
            if (errno == EINTR) continue;
            c->dead = 1;
            h2_fail("cannot read from %s: %s", c->addr, strerror(errno));
            return retry ? H2_RETRY : H2_TRANSPORT;
        }
        c->in.len += (size_t)k;
    }
}

/* connection-level frames; returns 1 if handled, 0 if not, or a failure */
static int h2_client_control(h2_client *c, const h2_fr *f, uint32_t id) {
    h2_buf out = {0};
    int handled = 0, rc = H2_OK;
    if (f->type == H2_SETTINGS && f->stream == 0) {
        handled = 1;
        if (!(f->flags & H2_ACK)) {
            int64_t delta;
            if (!h2_settings(&c->peer, f->p, f->n, &delta)) { c->dead = 1; return H2_TRANSPORT; }
            c->stream_window += delta;
            h2_frame(&out, H2_SETTINGS, H2_ACK, 0, 0, 0);
        }
    } else if (f->type == H2_PING) {
        handled = 1;
        if (!(f->flags & H2_ACK)) h2_frame(&out, H2_PING, H2_ACK, 0, f->p, f->n);
    } else if (f->type == H2_WINDOW_UPDATE && f->n == 4) {
        handled = 1;
        int64_t inc = h2_rd32(f->p) & 0x7fffffffu;
        if (f->stream == 0) c->conn_window += inc;
        else if (f->stream == id) c->stream_window += inc;
    }
    if (out.len) rc = h2_client_send(c, &out, 0);
    h2b_free(&out);
    return rc != H2_OK ? rc : handled;
}

/* a unary call on a connection: 0 and the response message in *resp, a
 * gRPC status (> 0) with the message in h2_err, or a failure kind (< 0) */
static int h2_client_unary(h2_client *c, const char *path, const char *fp, const unsigned char *msg, size_t n,
                           h2_buf *resp) {
    if (c->next_stream > 0x7fff0000u) { c->dead = 1; h2_fail("connection exhausted"); return H2_RETRY; }
    uint32_t id = c->next_stream;
    c->next_stream += 2;
    c->stream_window = c->peer.init_window;
    h2_buf block = {0}, out = {0}, body = {0}, data = {0}, hb = {0};
    h2_hdrs hs = {0};
    int rc = H2_OK, got_any = 0, ended = 0, end_after_block = 0, in_block = 0;
    size_t consumed = 0;
    h2_hpack_lit(&block, ":method", "POST");
    h2_hpack_lit(&block, ":scheme", "http");
    h2_hpack_lit(&block, ":path", path);
    h2_hpack_lit(&block, ":authority", c->addr);
    h2_hpack_lit(&block, "content-type", "application/grpc");
    h2_hpack_lit(&block, "te", "trailers");
    if (fp) h2_hpack_lit(&block, "fwp-fingerprint", fp);
    h2_header_frames(&out, id, &block, 0, c->peer.max_frame);
    rc = h2_client_send(c, &out, 1);
    h2_grpc_frame(&body, msg, n);
    size_t sent = 0;
    while (rc == H2_OK && sent < body.len) {
        int64_t avail = c->conn_window < c->stream_window ? c->conn_window : c->stream_window;
        if (avail > (int64_t)c->peer.max_frame) avail = (int64_t)c->peer.max_frame;
        if (avail <= 0) {
            h2_fr f;
            rc = h2_client_read(c, &f, &consumed, !got_any);
            if (rc != H2_OK) break;
            int h = h2_client_control(c, &f, id);
            if (h < 0) { rc = h; break; }
            if (!h && f.stream == id) {
                got_any = 1;
                if (f.type == H2_RST_STREAM) { rc = H2_TRANSPORT; h2_fail("stream reset by %s", c->addr); }
            }
            if (f.type == H2_GOAWAY) c->dead = 1;
            continue;
        }
        size_t k = (size_t)avail < body.len - sent ? (size_t)avail : body.len - sent;
        out.len = 0;
        h2_frame(&out, H2_DATA, sent + k == body.len ? H2_END_STREAM : 0, id, body.d + sent, k);
        rc = h2_client_send(c, &out, !got_any);
        sent += k;
        c->conn_window -= (int64_t)k;
        c->stream_window -= (int64_t)k;
    }
    while (rc == H2_OK && !ended) {
        h2_fr f;
        rc = h2_client_read(c, &f, &consumed, !got_any);
        if (rc != H2_OK) break;
        int h = h2_client_control(c, &f, id);
        if (h < 0) { rc = h; break; }
        if (h) continue;
        if (f.type == H2_GOAWAY && f.n >= 8) {
            c->dead = 1;
            if ((h2_rd32(f.p) & 0x7fffffffu) < id) {
                h2_fail("%s is shutting down", c->addr);
                rc = got_any ? H2_TRANSPORT : H2_RETRY;
            }
        } else if ((f.type == H2_HEADERS || f.type == H2_CONTINUATION) && f.stream == id) {
            got_any = 1;
            const unsigned char *p = f.p;
            size_t pn = f.n;
            if (f.type == H2_HEADERS) {
                if (f.flags & H2_END_STREAM) end_after_block = 1;
                if (!h2_unpad(&f, &p, &pn)) { rc = H2_TRANSPORT; h2_fail("bad HEADERS frame"); break; }
                hb.len = 0;
            } else if (!in_block) {
                rc = H2_TRANSPORT;
                h2_fail("unexpected CONTINUATION");
                break;
            }
            in_block = 1;
            h2b_put(&hb, p, pn);
            if (f.flags & H2_END_HEADERS) {
                in_block = 0;
                if (!h2_hpack_decode(&c->dec, hb.d, hb.len, &hs)) { c->dead = 1; rc = H2_TRANSPORT; break; }
                ended = end_after_block;
            }
        } else if (f.type == H2_HEADERS || f.type == H2_CONTINUATION) {
            /* another stream's header block: decode to keep HPACK in step */
            if (f.flags & H2_END_HEADERS) {
                const unsigned char *p = f.p;
                size_t pn = f.n;
                h2_hdrs tmp = {0};
                if (f.type != H2_HEADERS || h2_unpad(&f, &p, &pn)) h2_hpack_decode(&c->dec, p, pn, &tmp);
                h2_hdrs_free(&tmp);
            }
        } else if (f.type == H2_DATA && f.stream == id) {
            got_any = 1;
            const unsigned char *p;
            size_t pn;
            if (!h2_unpad(&f, &p, &pn)) { rc = H2_TRANSPORT; h2_fail("bad DATA frame"); break; }
            h2b_put(&data, p, pn);
            if (f.n > 0) {
                h2_buf w = {0}, fr = {0};
                h2b_be32(&w, (uint32_t)f.n);
                h2_frame(&fr, H2_WINDOW_UPDATE, 0, 0, w.d, 4);
                rc = h2_client_send(c, &fr, 0);
                h2b_free(&w);
                h2b_free(&fr);
            }
            if (f.flags & H2_END_STREAM) ended = 1;
        } else if (f.type == H2_RST_STREAM && f.stream == id) {
            int code = f.n >= 4 ? (int)h2_rd32(f.p) : 0;
            h2_fail("stream reset by %s (code %d)", c->addr, code);
            rc = code == 7 && !got_any ? H2_RETRY : H2_TRANSPORT;
        }
    }
    if (consumed) h2b_drop(&c->in, consumed);
    if (rc == H2_OK) {
        const char *st = h2_get(&hs, ":status");
        const char *gs = h2_get(&hs, "grpc-status");
        if (st && strcmp(st, "200") != 0) {
            h2_fail("HTTP status %s from %s", st, c->addr);
            rc = GRPC_UNAVAILABLE;
        } else if (!gs) {
            h2_fail("no grpc-status from %s", c->addr);
            rc = GRPC_INTERNAL;
        } else if (atoi(gs) != 0) {
            const char *m = h2_get(&hs, "grpc-message");
            char *dm = strdup(m ? m : "");
            h2_pct_decode(dm);
            h2_fail("%s", dm);
            free(dm);
            rc = atoi(gs) > 0 ? atoi(gs) : 2;
        } else {
            const unsigned char *m;
            size_t mn;
            if (!h2_grpc_unframe(&data, &m, &mn)) rc = GRPC_INTERNAL;
            else { resp->len = 0; h2b_put(resp, m, mn); }
        }
    }
    h2b_free(&block);
    h2b_free(&out);
    h2b_free(&body);
    h2b_free(&data);
    h2b_free(&hb);
    h2_hdrs_free(&hs);
    return rc;
}

/* a unary call to `addr` on a pooled connection; the result is as for
 * h2_client_unary, with H2_TRANSPORT for connection failures */
static int h2_call(const char *addr, const char *path, const char *fp, const unsigned char *msg, size_t n,
                   h2_buf *resp) {
    for (int attempt = 0; attempt < 2; attempt++) {
        h2_client *c = 0, **pp = &h2_pool;
        for (; *pp; pp = &(*pp)->next)
            if (strcmp((*pp)->addr, addr) == 0) { c = *pp; *pp = c->next; break; }
        int reused = c != 0;
        if (!c) c = h2_client_new(addr);
        if (!c) return H2_TRANSPORT;
        int rc = h2_client_unary(c, path, fp, msg, n, resp);
        if (c->dead) h2_client_free(c);
        else { c->next = h2_pool; h2_pool = c; }
        if (rc == H2_RETRY && reused && attempt == 0) continue;
        return rc == H2_RETRY ? H2_TRANSPORT : rc;
    }
    return H2_TRANSPORT;
}

/* ------------------------------------------------------------------- server */

/* a call: returns 0 with the response message in *out, or a gRPC status
 * with its message in *err (malloc'd) */
typedef int (*h2_handler)(void *ctx, const char *path, const h2_hdrs *hs, const unsigned char *msg, size_t n,
                          h2_buf *out, char **err);

typedef struct h2_sstream {
    uint32_t id;
    h2_hdrs hs;
    h2_buf data, pending, trailers;
    int ended, dispatched, has_trailers;
    int64_t window;
    struct h2_sstream *next;
} h2_sstream;

typedef struct {
    int fd;
    h2_buf in, out;
    int preface, closing, closed;
    h2_hpack dec;
    h2_peer peer;
    int64_t conn_window;
    h2_sstream *streams; /* by increasing id */
    uint32_t cont_stream, last_stream;
    int cont_active, cont_end;
    h2_buf cont;
} h2_sconn;

static void h2_sstream_free(h2_sstream *s) {
    h2_hdrs_free(&s->hs);
    h2b_free(&s->data);
    h2b_free(&s->pending);
    h2b_free(&s->trailers);
    free(s);
}

static h2_sstream *h2_find(h2_sconn *c, uint32_t id) {
    for (h2_sstream *s = c->streams; s; s = s->next)
        if (s->id == id) return s;
    return 0;
}

static void h2_remove(h2_sconn *c, uint32_t id) {
    for (h2_sstream **pp = &c->streams; *pp; pp = &(*pp)->next)
        if ((*pp)->id == id) {
            h2_sstream *s = *pp;
            *pp = s->next;
            h2_sstream_free(s);
            return;
        }
}

static void h2_goaway(h2_sconn *c, uint32_t code) {
    h2_buf p = {0};
    h2b_be32(&p, c->last_stream);
    h2b_be32(&p, code);
    h2_frame(&c->out, H2_GOAWAY, 0, 0, p.d, p.len);
    h2b_free(&p);
    c->closing = 1;
}

static void h2_header_block(h2_sconn *c, uint32_t id, const unsigned char *b, size_t n, int end) {
    h2_hdrs hs = {0};
    if (!h2_hpack_decode(&c->dec, b, n, &hs)) {
        h2_hdrs_free(&hs);
        h2_goaway(c, 9); /* COMPRESSION_ERROR */
        return;
    }
    h2_sstream *s = h2_find(c, id);
    if (s) { /* trailers of a request */
        if (end) s->ended = 1;
        h2_hdrs_free(&hs);
        return;
    }
    if (id % 2 == 0 || id <= c->last_stream) { h2_hdrs_free(&hs); return; }
    c->last_stream = id;
    s = (h2_sstream *)calloc(1, sizeof *s);
    s->id = id;
    s->hs = hs;
    s->ended = end;
    s->window = c->peer.init_window;
    h2_sstream **pp = &c->streams;
    while (*pp) pp = &(*pp)->next;
    *pp = s;
}

static void h2_on_frame(h2_sconn *c, const h2_fr *f) {
    if (c->cont_active && (f->type != H2_CONTINUATION || f->stream != c->cont_stream)) { h2_goaway(c, 1); return; }
    const unsigned char *p;
    size_t n;
    switch (f->type) {
    case H2_HEADERS:
        if (!h2_unpad(f, &p, &n)) { h2_goaway(c, 1); return; }
        if (f->flags & H2_END_HEADERS) {
            h2_header_block(c, f->stream, p, n, f->flags & H2_END_STREAM);
        } else {
            c->cont_active = 1;
            c->cont_stream = f->stream;
            c->cont_end = f->flags & H2_END_STREAM;
            c->cont.len = 0;
            h2b_put(&c->cont, p, n);
        }
        break;
    case H2_CONTINUATION:
        if (!c->cont_active) { h2_goaway(c, 1); return; }
        h2b_put(&c->cont, f->p, f->n);
        if (f->flags & H2_END_HEADERS) {
            c->cont_active = 0;
            h2_header_block(c, c->cont_stream, c->cont.d, c->cont.len, c->cont_end);
        }
        break;
    case H2_DATA: {
        if (!h2_unpad(f, &p, &n)) { h2_goaway(c, 1); return; }
        if (f->n > 0) {
            h2_buf w = {0};
            h2b_be32(&w, (uint32_t)f->n);
            h2_frame(&c->out, H2_WINDOW_UPDATE, 0, 0, w.d, 4);
            h2b_free(&w);
        }
        h2_sstream *s = h2_find(c, f->stream);
        if (s) {
            h2b_put(&s->data, p, n);
            if (f->flags & H2_END_STREAM) s->ended = 1;
        }
        break;
    }
    case H2_RST_STREAM:
        h2_remove(c, f->stream);
        break;
    case H2_SETTINGS:
        if (!(f->flags & H2_ACK)) {
            int64_t delta;
            if (!h2_settings(&c->peer, f->p, f->n, &delta)) { h2_goaway(c, 1); return; }
            for (h2_sstream *s = c->streams; s; s = s->next) s->window += delta;
            h2_frame(&c->out, H2_SETTINGS, H2_ACK, 0, 0, 0);
        }
        break;
    case H2_PING:
        if (!(f->flags & H2_ACK)) h2_frame(&c->out, H2_PING, H2_ACK, 0, f->p, f->n);
        break;
    case H2_WINDOW_UPDATE:
        if (f->n == 4) {
            int64_t inc = h2_rd32(f->p) & 0x7fffffffu;
            if (f->stream == 0) c->conn_window += inc;
            else {
                h2_sstream *s = h2_find(c, f->stream);
                if (s) s->window += inc;
            }
        }
        break;
    case H2_GOAWAY:
        c->closing = 1;
        break;
    default:
        break;
    }
}

static void h2_process_input(h2_sconn *c) {
    size_t plen = sizeof h2_preface - 1;
    if (!c->preface) {
        size_t k = c->in.len < plen ? c->in.len : plen;
        if (k && memcmp(c->in.d, h2_preface, k) != 0) { c->closed = 1; return; }
        if (c->in.len < plen) return;
        h2b_drop(&c->in, plen);
        c->preface = 1;
    }
    for (;;) {
        h2_fr f;
        size_t size;
        int r = h2_parse(&c->in, &f, &size);
        if (r == 0) return;
        if (r < 0) { h2_goaway(c, 6); c->in.len = 0; return; }
        h2_on_frame(c, &f);
        h2b_drop(&c->in, size);
        if (c->closing && !c->streams) return;
    }
}

static void h2_dispatch(h2_sconn *c, h2_handler handler, void *ctx) {
    for (;;) {
        h2_sstream *s = c->streams;
        while (s && !(s->ended && !s->dispatched)) s = s->next;
        if (!s) return;
        s->dispatched = 1;
        const char *ct = h2_get(&s->hs, "content-type");
        const char *path = h2_get(&s->hs, ":path");
        const char *method = h2_get(&s->hs, ":method");
        h2_buf block = {0};
        if (!method || strcmp(method, "POST") != 0 || !ct || strncmp(ct, "application/grpc", 16) != 0) {
            h2_hpack_lit(&block, ":status", "415");
            h2_header_frames(&c->out, s->id, &block, 1, c->peer.max_frame);
            h2b_free(&block);
            h2_remove(c, s->id);
            continue;
        }
        const unsigned char *msg;
        size_t mn;
        h2_buf resp = {0};
        char *err = 0;
        int status;
        if (!h2_grpc_unframe(&s->data, &msg, &mn)) {
            status = GRPC_INVALID_ARGUMENT;
            err = strdup(h2_err);
        } else {
            status = handler(ctx, path ? path : "", &s->hs, msg, mn, &resp, &err);
        }
        h2_hpack_lit(&block, ":status", "200");
        h2_hpack_lit(&block, "content-type", "application/grpc");
        if (status == 0) {
            h2_header_frames(&c->out, s->id, &block, 0, c->peer.max_frame);
            h2_grpc_frame(&s->pending, resp.d, resp.len);
            h2_hpack_lit(&s->trailers, "grpc-status", "0");
            s->has_trailers = 1;
        } else {
            char code[16];
            snprintf(code, sizeof code, "%d", status);
            h2_buf m = {0};
            h2_pct_encode(&m, err ? err : "");
            h2_hpack_lit(&block, "grpc-status", code);
            h2_hpack_lit(&block, "grpc-message", (const char *)m.d);
            h2_header_frames(&c->out, s->id, &block, 1, c->peer.max_frame);
            h2b_free(&m);
            h2_remove(c, s->id);
        }
        free(err);
        h2b_free(&resp);
        h2b_free(&block);
    }
}

static void h2_flush_streams(h2_sconn *c) {
    h2_sstream *s = c->streams;
    while (s) {
        h2_sstream *next = s->next;
        if (s->has_trailers) {
            while (s->pending.len > 0) {
                int64_t k = c->conn_window < s->window ? c->conn_window : s->window;
                if (k > (int64_t)c->peer.max_frame) k = (int64_t)c->peer.max_frame;
                if (k > (int64_t)s->pending.len) k = (int64_t)s->pending.len;
                if (k <= 0) break;
                h2_frame(&c->out, H2_DATA, 0, s->id, s->pending.d, (size_t)k);
                h2b_drop(&s->pending, (size_t)k);
                c->conn_window -= k;
                s->window -= k;
            }
            if (s->pending.len == 0) {
                h2_header_frames(&c->out, s->id, &s->trailers, 1, c->peer.max_frame);
                h2_remove(c, s->id);
            }
        }
        s = next;
    }
}

static void h2_read_some(h2_sconn *c) {
    for (;;) {
        h2b_reserve(&c->in, 65536);
        ssize_t k = recv(c->fd, c->in.d + c->in.len, 65536, 0);
        if (k == 0) { c->closed = 1; return; }
        if (k < 0) {
            if (errno == EINTR) continue;
            if (errno != EAGAIN && errno != EWOULDBLOCK) c->closed = 1;
            return;
        }
        c->in.len += (size_t)k;
    }
}

static void h2_write_some(h2_sconn *c) {
    while (c->out.len > 0) {
        ssize_t k = send(c->fd, c->out.d, c->out.len, MSG_NOSIGNAL);
        if (k < 0) {
            if (errno == EINTR) continue;
            if (errno != EAGAIN && errno != EWOULDBLOCK) c->closed = 1;
            return;
        }
        h2b_drop(&c->out, (size_t)k);
    }
    if (c->closing && !c->streams) c->closed = 1;
}

static void h2_sconn_free(h2_sconn *c) {
    close(c->fd);
    h2b_free(&c->in);
    h2b_free(&c->out);
    h2b_free(&c->cont);
    h2_hpack_free(&c->dec);
    while (c->streams) h2_remove(c, c->streams->id);
    free(c);
}

/* bind "host:port"; the bound address is written to `bound` */
static int h2_listen(const char *addr, char *bound, size_t bn) {
    char host[256];
    const char *colon = strrchr(addr, ':');
    if (!colon || (size_t)(colon - addr) >= sizeof host) { h2_fail("bad address `%s`", addr); return -1; }
    memcpy(host, addr, (size_t)(colon - addr));
    host[colon - addr] = 0;
    char *h = host;
    if (h[0] == '[' && h[strlen(h) - 1] == ']') { h[strlen(h) - 1] = 0; h++; }
    struct addrinfo hints, *res = 0;
    memset(&hints, 0, sizeof hints);
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;
    int rc = getaddrinfo(*h ? h : 0, colon + 1, &hints, &res);
    if (rc != 0) { h2_fail("cannot resolve %s: %s", addr, gai_strerror(rc)); return -1; }
    int fd = -1, err = 0;
    for (struct addrinfo *a = res; a; a = a->ai_next) {
        fd = socket(a->ai_family, a->ai_socktype | SOCK_CLOEXEC, a->ai_protocol);
        if (fd < 0) { err = errno; continue; }
        int one = 1;
        setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);
        if (bind(fd, a->ai_addr, a->ai_addrlen) == 0 && listen(fd, 128) == 0) break;
        err = errno;
        close(fd);
        fd = -1;
    }
    freeaddrinfo(res);
    if (fd < 0) { h2_fail("cannot listen on %s: %s", addr, strerror(err)); return -1; }
    struct sockaddr_storage ss;
    socklen_t sl = sizeof ss;
    char hb[128], pb[16];
    if (getsockname(fd, (struct sockaddr *)&ss, &sl) == 0 &&
        getnameinfo((struct sockaddr *)&ss, sl, hb, sizeof hb, pb, sizeof pb, NI_NUMERICHOST | NI_NUMERICSERV) == 0)
        snprintf(bound, bn, ss.ss_family == AF_INET6 ? "[%s]:%s" : "%s:%s", hb, pb);
    else
        snprintf(bound, bn, "%s", addr);
    return fd;
}

/* serve calls on a listening socket forever */
static int h2_serve(int lfd, h2_handler handler, void *ctx) {
    fcntl(lfd, F_SETFL, fcntl(lfd, F_GETFL) | O_NONBLOCK);
    h2_sconn **conns = 0;
    size_t nc = 0, cap = 0;
    struct pollfd *fds = 0;
    for (;;) {
        fds = (struct pollfd *)realloc(fds, (nc + 1) * sizeof *fds);
        fds[0].fd = lfd;
        fds[0].events = POLLIN;
        fds[0].revents = 0;
        for (size_t i = 0; i < nc; i++) {
            fds[i + 1].fd = conns[i]->fd;
            fds[i + 1].events = (short)(POLLIN | (conns[i]->out.len ? POLLOUT : 0));
            fds[i + 1].revents = 0;
        }
        if (poll(fds, (nfds_t)(nc + 1), -1) < 0) {
            if (errno == EINTR) continue;
            h2_fail("poll: %s", strerror(errno));
            return 0;
        }
        for (size_t i = 0; i < nc; i++) {
            h2_sconn *c = conns[i];
            short ev = fds[i + 1].revents;
            if (!ev) continue;
            if (ev & (POLLIN | POLLHUP | POLLERR)) {
                h2_read_some(c);
                h2_process_input(c);
                h2_dispatch(c, handler, ctx);
            }
            h2_flush_streams(c);
            h2_write_some(c);
        }
        size_t k = 0;
        for (size_t i = 0; i < nc; i++) {
            if (conns[i]->closed) h2_sconn_free(conns[i]);
            else conns[k++] = conns[i];
        }
        nc = k;
        if (fds[0].revents & POLLIN) {
            for (;;) {
                int fd = accept(lfd, 0, 0);
                if (fd < 0) break;
                int one = 1;
                setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof one);
                fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK);
                fcntl(fd, F_SETFD, FD_CLOEXEC);
                h2_sconn *c = (h2_sconn *)calloc(1, sizeof *c);
                c->fd = fd;
                h2_hpack_init(&c->dec);
                c->peer.max_frame = 16384;
                c->peer.init_window = 65535;
                c->conn_window = 65535;
                h2_our_settings(&c->out);
                h2_write_some(c);
                if (nc == cap) {
                    cap = cap ? cap * 2 : 16;
                    conns = (h2_sconn **)realloc(conns, cap * sizeof *conns);
                }
                conns[nc++] = c;
            }
        }
    }
}

/* ----------------------------------------------------------------- protobuf */

/* Schema kinds (src/protobuf.rs, Schema::flatten). */
enum { PB_BOOL, PB_SINT, PB_UINT, PB_F32, PB_F64, PB_STR, PB_BYTES, PB_INT128, PB_MSG, PB_ONEOF, PB_LIST, PB_OPT };

typedef struct { const unsigned char *d; size_t n, i; } pb_rd;

static int pb_take(pb_rd *r, size_t k, const unsigned char **p) {
    if (k > r->n - r->i) return h2_fail("truncated value");
    *p = r->d + r->i;
    r->i += k;
    return 1;
}

static int pb_leb(pb_rd *r, uint64_t *x) {
    *x = 0;
    for (int shift = 0; shift < 64; shift += 7) {
        const unsigned char *b;
        if (!pb_take(r, 1, &b)) return 0;
        *x |= (uint64_t)(b[0] & 0x7f) << shift;
        if (!(b[0] & 0x80)) return 1;
    }
    return h2_fail("bad varint");
}

static void pb_varint(h2_buf *b, uint64_t x) {
    while (x >= 0x80) { h2b_byte(b, (unsigned)(x & 0x7f) | 0x80); x >>= 7; }
    h2b_byte(b, (unsigned)x);
}

static void pb_key(h2_buf *b, uint32_t num, int wire) { pb_varint(b, (uint64_t)num << 3 | (unsigned)wire); }

static int pb_le(pb_rd *r, int w, uint64_t *x) {
    const unsigned char *p;
    if (!pb_take(r, (size_t)w, &p)) return 0;
    *x = 0;
    for (int i = 0; i < w; i++) *x |= (uint64_t)p[i] << (8 * i);
    return 1;
}

static int pb_packable(const int *S, int node) { int k = S[node]; return k <= PB_F64; }

/* a scalar: wire type, bytes in *b, and whether it is the default */
static int pb_enc_scalar(const int *S, int node, pb_rd *r, h2_buf *b, int *wire, int *dflt) {
    uint64_t x;
    const unsigned char *p;
    switch (S[node]) {
    case PB_BOOL:
        if (!pb_leb(r, &x)) return 0;
        pb_varint(b, x); *wire = 0; *dflt = x == 0; return 1;
    case PB_SINT: {
        int w = S[node + 1];
        if (!pb_le(r, w, &x)) return 0;
        int shift = 64 - 8 * w;
        int64_t v = (int64_t)(x << shift) >> shift;
        pb_varint(b, ((uint64_t)v << 1) ^ (uint64_t)(v >> 63)); *wire = 0; *dflt = v == 0; return 1;
    }
    case PB_UINT:
        if (!pb_le(r, S[node + 1], &x)) return 0;
        pb_varint(b, x); *wire = 0; *dflt = x == 0; return 1;
    case PB_F32: case PB_F64: {
        int w = S[node] == PB_F32 ? 4 : 8;
        if (!pb_take(r, (size_t)w, &p)) return 0;
        h2b_put(b, p, (size_t)w);
        *wire = w == 4 ? 5 : 1;
        *dflt = 1;
        for (int i = 0; i < w; i++) if (p[i]) *dflt = 0;
        return 1;
    }
    case PB_STR: case PB_BYTES:
        if (!pb_leb(r, &x) || !pb_take(r, (size_t)x, &p)) return 0;
        pb_varint(b, x); h2b_put(b, p, (size_t)x); *wire = 2; *dflt = x == 0; return 1;
    case PB_INT128:
        if (!pb_take(r, 16, &p)) return 0;
        pb_varint(b, 16); h2b_put(b, p, 16); *wire = 2;
        *dflt = 1;
        for (int i = 0; i < 16; i++) if (p[i]) *dflt = 0;
        return 1;
    }
    return h2_fail("internal: not a scalar");
}

static int pb_enc_body(const int *S, int node, pb_rd *r, h2_buf *out);

static int pb_enc_field(const int *S, uint32_t num, int node, pb_rd *r, h2_buf *out, int presence) {
    uint64_t x;
    switch (S[node]) {
    case PB_MSG: case PB_ONEOF: {
        h2_buf sub = {0};
        int ok = pb_enc_body(S, node, r, &sub);
        if (ok) { pb_key(out, num, 2); pb_varint(out, sub.len); h2b_put(out, sub.d, sub.len); }
        h2b_free(&sub);
        return ok;
    }
    case PB_LIST: {
        int c = S[node + 1];
        if (!pb_leb(r, &x)) return 0;
        if (pb_packable(S, c)) {
            h2_buf buf = {0};
            int wire, dflt, ok = 1;
            for (uint64_t i = 0; ok && i < x; i++) ok = pb_enc_scalar(S, c, r, &buf, &wire, &dflt);
            if (ok && x > 0) { pb_key(out, num, 2); pb_varint(out, buf.len); h2b_put(out, buf.d, buf.len); }
            h2b_free(&buf);
            return ok;
        }
        for (uint64_t i = 0; i < x; i++) if (!pb_enc_field(S, num, c, r, out, 1)) return 0;
        return 1;
    }
    case PB_OPT:
        if (!pb_leb(r, &x)) return 0;
        return x == 1 ? pb_enc_field(S, num, S[node + 1], r, out, 1) : 1;
    default: {
        h2_buf b = {0};
        int wire, dflt;
        int ok = pb_enc_scalar(S, node, r, &b, &wire, &dflt);
        if (ok && (presence || !dflt)) { pb_key(out, num, wire); h2b_put(out, b.d, b.len); }
        h2b_free(&b);
        return ok;
    }
    }
}

static int pb_enc_body(const int *S, int node, pb_rd *r, h2_buf *out) {
    int n = S[node + 1];
    if (S[node] == PB_MSG) {
        /* canonical order in, field number order out */
        h2_buf *parts = (h2_buf *)calloc((size_t)n + 1, sizeof(h2_buf));
        int ok = 1;
        for (int i = 0; ok && i < n; i++)
            ok = pb_enc_field(S, (uint32_t)S[node + 2 + 2 * i], S[node + 3 + 2 * i], r, &parts[i], 0);
        for (int done = 0; ok && done < n; done++) {
            int best = -1;
            for (int i = 0; i < n; i++)
                if (parts[i].cap != (size_t)-1 && (best < 0 || S[node + 2 + 2 * i] < S[node + 2 + 2 * best])) best = i;
            h2b_put(out, parts[best].d, parts[best].len);
            h2b_free(&parts[best]);
            parts[best].cap = (size_t)-1;
        }
        for (int i = 0; i < n; i++) if (parts[i].cap != (size_t)-1) h2b_free(&parts[i]);
        free(parts);
        return ok;
    }
    if (S[node] == PB_ONEOF) {
        uint64_t tag;
        if (!pb_leb(r, &tag)) return 0;
        if (tag >= (uint64_t)n) return h2_fail("bad constructor tag");
        return pb_enc_field(S, (uint32_t)tag + 1, S[node + 2 + (int)tag], r, out, 1);
    }
    return h2_fail("internal: not a message");
}

/* canonical bytes -> the body of message node `node` */
static int pb_encode(const int *S, int node, const unsigned char *canon, size_t n, h2_buf *out) {
    pb_rd r = {canon, n, 0};
    if (!pb_enc_body(S, node, &r, out)) return 0;
    if (r.i != n) return h2_fail("trailing bytes after value");
    return 1;
}

/* a field on the wire */
typedef struct { uint32_t num; int wire; uint64_t v; const unsigned char *p; size_t n; } pb_field;

/* the next field of a body: 1, 0 at the end, -1 malformed */
static int pb_next(const unsigned char *b, size_t n, size_t *i, pb_field *f) {
    if (*i >= n) return 0;
    pb_rd r = {b, n, *i};
    uint64_t k;
    if (!pb_leb(&r, &k)) return -1;
    if ((k >> 3) == 0 || (k >> 3) > 0xffffffffu) { h2_fail("bad field number"); return -1; }
    f->num = (uint32_t)(k >> 3);
    f->wire = (int)(k & 7);
    switch (f->wire) {
    case 0: if (!pb_leb(&r, &f->v)) return -1; break;
    case 1: if (!pb_le(&r, 8, &f->v)) return -1; break;
    case 5: if (!pb_le(&r, 4, &f->v)) return -1; break;
    case 2:
        if (!pb_leb(&r, &f->v) || !pb_take(&r, (size_t)f->v, &f->p)) return -1;
        f->n = (size_t)f->v;
        break;
    default: h2_fail("unsupported wire type"); return -1;
    }
    *i = r.i;
    return 1;
}

static void pb_le_put(h2_buf *b, uint64_t x, int w) {
    for (int i = 0; i < w; i++) h2b_byte(b, (unsigned)(x >> (8 * i)) & 0xff);
}

static int pb_valid_utf8(const unsigned char *s, size_t n) {
    size_t i = 0;
    while (i < n) {
        unsigned char c = s[i];
        int k;
        uint32_t cp;
        if (c < 0x80) { i++; continue; }
        else if ((c & 0xe0) == 0xc0) { k = 1; cp = c & 0x1f; }
        else if ((c & 0xf0) == 0xe0) { k = 2; cp = c & 0x0f; }
        else if ((c & 0xf8) == 0xf0) { k = 3; cp = c & 0x07; }
        else return 0;
        if (i + (size_t)k >= n) return 0;
        for (int j = 1; j <= k; j++) {
            if ((s[i + (size_t)j] & 0xc0) != 0x80) return 0;
            cp = cp << 6 | (s[i + (size_t)j] & 0x3f);
        }
        if ((k == 1 && cp < 0x80) || (k == 2 && cp < 0x800) || (k == 3 && cp < 0x10000) || cp > 0x10ffff ||
            (cp >= 0xd800 && cp <= 0xdfff))
            return 0;
        i += (size_t)k + 1;
    }
    return 1;
}

static int pb_dec_scalar(const int *S, int node, uint32_t num, const pb_field *f, h2_buf *out) {
    int k = S[node];
    int want = (k == PB_F32) ? 5 : (k == PB_F64) ? 1 : (k >= PB_STR) ? 2 : 0;
    if (f->wire != want) return h2_fail("field %u: wrong wire type", num);
    switch (k) {
    case PB_BOOL: h2b_byte(out, f->v != 0); return 1;
    case PB_SINT: {
        int w = S[node + 1];
        int64_t v = (int64_t)(f->v >> 1) ^ -(int64_t)(f->v & 1);
        if (w < 8) {
            int64_t lim = (int64_t)1 << (8 * w - 1);
            if (v < -lim || v >= lim) return h2_fail("field %u: value out of range", num);
        }
        pb_le_put(out, (uint64_t)v, w);
        return 1;
    }
    case PB_UINT: {
        int w = S[node + 1];
        if (w < 8 && f->v >= ((uint64_t)1 << (8 * w))) return h2_fail("field %u: value out of range", num);
        pb_le_put(out, f->v, w);
        return 1;
    }
    case PB_F32: pb_le_put(out, f->v, 4); return 1;
    case PB_F64: pb_le_put(out, f->v, 8); return 1;
    case PB_STR:
        if (!pb_valid_utf8(f->p, f->n)) return h2_fail("field %u: invalid UTF-8", num);
        /* fall through */
    case PB_BYTES:
        pb_varint(out, f->n);
        h2b_put(out, f->p, f->n);
        return 1;
    case PB_INT128:
        if (f->n == 0) { for (int i = 0; i < 16; i++) h2b_byte(out, 0); return 1; }
        if (f->n != 16) return h2_fail("field %u: value out of range", num);
        h2b_put(out, f->p, 16);
        return 1;
    }
    return h2_fail("internal: not a scalar");
}

static int pb_dec_body(const int *S, int node, const unsigned char *b, size_t n, h2_buf *out);

static int pb_dec_value(const int *S, int node, uint32_t num, const pb_field *f, h2_buf *out) {
    if (S[node] == PB_MSG || S[node] == PB_ONEOF) {
        if (f->wire != 2) return h2_fail("field %u: wrong wire type", num);
        return pb_dec_body(S, node, f->p, f->n, out);
    }
    return pb_dec_scalar(S, node, num, f, out);
}

static int pb_default(const int *S, int node, uint32_t num, h2_buf *out) {
    switch (S[node]) {
    case PB_BOOL: case PB_STR: case PB_BYTES: case PB_LIST: case PB_OPT: h2b_byte(out, 0); return 1;
    case PB_SINT: case PB_UINT: for (int i = 0; i < S[node + 1]; i++) h2b_byte(out, 0); return 1;
    case PB_F32: for (int i = 0; i < 4; i++) h2b_byte(out, 0); return 1;
    case PB_F64: for (int i = 0; i < 8; i++) h2b_byte(out, 0); return 1;
    case PB_INT128: for (int i = 0; i < 16; i++) h2b_byte(out, 0); return 1;
    case PB_MSG:
        for (int i = 0; i < S[node + 1]; i++)
            if (!pb_default(S, S[node + 3 + 2 * i], (uint32_t)S[node + 2 + 2 * i], out)) return 0;
        return 1;
    }
    return h2_fail("field %u: missing value", num);
}

static int pb_dec_field(const int *S, uint32_t num, int node, const unsigned char *b, size_t n, h2_buf *out) {
    size_t i = 0;
    pb_field f, last;
    int have = 0, r;
    if (S[node] == PB_LIST) {
        int c = S[node + 1];
        h2_buf buf = {0};
        uint64_t count = 0;
        int ok = 1;
        while (ok && (r = pb_next(b, n, &i, &f)) > 0) {
            if (f.num != num) continue;
            if (f.wire == 2 && pb_packable(S, c)) {
                pb_rd pr = {f.p, f.n, 0};
                while (ok && pr.i < pr.n) {
                    pb_field e;
                    e.num = num;
                    if (S[c] == PB_F32) { e.wire = 5; ok = pb_le(&pr, 4, &e.v); }
                    else if (S[c] == PB_F64) { e.wire = 1; ok = pb_le(&pr, 8, &e.v); }
                    else { e.wire = 0; ok = pb_leb(&pr, &e.v); }
                    ok = ok && pb_dec_scalar(S, c, num, &e, &buf);
                    count++;
                }
            } else {
                ok = pb_dec_value(S, c, num, &f, &buf);
                count++;
            }
        }
        if (ok && r < 0) ok = 0;
        if (ok) { pb_varint(out, count); h2b_put(out, buf.d, buf.len); }
        h2b_free(&buf);
        return ok;
    }
    while ((r = pb_next(b, n, &i, &f)) > 0)
        if (f.num == num) { last = f; have = 1; }
    if (r < 0) return 0;
    if (S[node] == PB_OPT) {
        if (!have) { h2b_byte(out, 0); return 1; }
        h2b_byte(out, 1);
        return pb_dec_value(S, S[node + 1], num, &last, out);
    }
    if (!have) return pb_default(S, node, num, out);
    return pb_dec_value(S, node, num, &last, out);
}

static int pb_dec_body(const int *S, int node, const unsigned char *b, size_t n, h2_buf *out) {
    int k = S[node + 1];
    if (S[node] == PB_MSG) {
        for (int i = 0; i < k; i++)
            if (!pb_dec_field(S, (uint32_t)S[node + 2 + 2 * i], S[node + 3 + 2 * i], b, n, out)) return 0;
        return 1;
    }
    if (S[node] == PB_ONEOF) {
        size_t i = 0;
        pb_field f, last;
        int have = 0, r;
        while ((r = pb_next(b, n, &i, &f)) > 0)
            if (f.num >= 1 && f.num <= (uint32_t)k) { last = f; have = 1; }
        if (r < 0) return 0;
        if (!have) return h2_fail("no alternative of a oneof is set");
        pb_varint(out, last.num - 1);
        return pb_dec_value(S, S[node + 2 + (int)last.num - 1], last.num, &last, out);
    }
    return h2_fail("internal: not a message");
}

/* the body of message node `node` -> canonical bytes */
static int pb_decode(const int *S, int node, const unsigned char *pb, size_t n, h2_buf *out) {
    return pb_dec_body(S, node, pb, n, out);
}

#endif /* __wasi__ */
