#!/usr/bin/env python3
"""Check tracked documentation, immutable roadmap ancestry and commit subjects.

Fetch full history and roadmap/preparation-* tags before checking a clean clone.
Run local checks through scripts/local-guard.py.
"""

import re
import subprocess
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True)


@lru_cache(maxsize=None)
def headings(path):
    anchors = set()
    counts = {}
    for heading in re.findall(r"^#{1,6} +(.+)$", path.read_text(), re.M):
        anchor = re.sub(r"[^\w -]", "", heading.lower()).replace(" ", "-")
        count = counts.get(anchor, 0)
        counts[anchor] = count + 1
        anchors.add(anchor if not count else f"{anchor}-{count}")
    return anchors


def check_links(name):
    source = ROOT / name
    for target in re.findall(r"\]\(([^)]+)\)", source.read_text()):
        target = target.split(" ")[0]
        path, _, fragment = target.partition("#")
        if "://" in path or path.startswith("/"):
            continue
        linked = source.parent / path if path else source
        assert linked.exists(), (name, target, "missing path")
        if fragment and linked.suffix == ".md":
            assert fragment in headings(linked), (name, target, "missing heading")


def check_subject(revision):
    message = git("cat-file", "commit", revision).split("\n\n", 1)[1]
    lines = message.splitlines()
    assert len(lines) == 1 and len(lines[0]) <= 80, (revision, message)
    forbidden = ("co-authored", "co authored", "authored-by", "authored by",
                 "ai attribution", "generated by ai", "generated by codex")
    assert not any(term in message.lower() for term in forbidden), (revision, message)


def check_handoff(queue):
    rows = set()
    for row in (ROOT / "docs/development-state.md").read_text().splitlines():
        match = re.match(r"^\| (\d+) [^|]+\|", row)
        if not match:
            continue
        number = int(match[1])
        fields = [field.strip().strip("`") for field in row.split("|")]
        branch = fields[1].split(maxsplit=1)[1]
        current, base = fields[2:4]
        assert number not in rows, (number, "duplicate live handoff row")
        rows.add(number)
        assert number in queue, (number, "handoff row missing from queue")
        queued_branch, queued_head = queue[number]
        assert branch == queued_branch, (number, branch, queued_branch)
        for revision in (current, base):
            assert re.fullmatch(r"[0-9a-f]{12,40}", revision), (number, revision)
        assert git("rev-parse", current).strip() == git("rev-parse", queued_head).strip(), (
            number, "handoff head differs from queue", current, queued_head)
        subprocess.run(["git", "merge-base", "--is-ancestor", base, current],
                       cwd=ROOT, check=True)
    return len(rows)


def main():
    files = git("ls-files", "*.md").splitlines()
    for name in files:
        check_links(name)
    revisions = {"HEAD"}
    rows = []
    queue = {}
    for row in (ROOT / "docs/roadmap-queue.md").read_text().splitlines():
        if not re.match(r"\| \d+ \|", row):
            continue
        fields = [field.strip().strip("`") for field in row.split("|")]
        number = int(fields[1])
        current, old, parent = fields[4:7]
        queue[number] = (fields[3], current)
        for revision in (current, old, parent):
            assert re.fullmatch(r"[0-9a-f]{12,40}", revision), (number, revision)
        subprocess.run(["git", "merge-base", "--is-ancestor", parent, old],
                       cwd=ROOT, check=True)
        tag = f"refs/tags/roadmap/preparation-{number:03d}"
        assert git("rev-parse", tag).strip() == git("rev-parse", old).strip(), (number, tag)
        revisions.update((current, old))
        rows.append(number)
    assert rows == list(range(rows[0], rows[-1] + 1)), ("queue order", rows)
    for revision in sorted(revisions):
        check_subject(revision)
    live = check_handoff(queue)
    print(f"{len(files)} doc link sets, {len(rows)} immutable queue pairs/tags and "
          f"{live} live heads/bases pass; commit messages pass")


if __name__ == "__main__":
    main()
